# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

name: bench

jobs:
  bench:
    timeout-minutes: 720
    runs-on: [self-hosted, gpu]

    container:
      image: nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04
      options: --gpus all

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TORCH_INSTALL: 1
      TORCH_TEST: 1
      DEBIAN_FRONTEND: 'noninteractive'
      R_KEEP_PKG_SOURCE: yes
      CUDA: '11.3'

    steps:

      - run: |
          apt-get update -y
          apt-get install -y sudo software-properties-common dialog apt-utils tzdata wget zip unzip
          add-apt-repository ppa:git-core/ppa -y
          apt-get update -y
          apt-get install -y git libopenblas-base libicu-dev

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set safe directory
        run: |
          git config --global --add safe.directory /__w/bench-torch/bench-torch

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Allow parallel compilation
        run: |
          echo "R_MAKEVARS_USER=$GITHUB_WORKSPACE/bench-torch/bench-torch/Makevars" >> $GITHUB_ENV
          echo "R_LIBS_USER=$GITHUB_WORKSPACE/bench-torch/bench-torch/rmainlib" >> $GITHUB_ENV

      - name: Install benchtorch
        run: |
          install.packages("pak")
          pak::pkg_install(".")
        shell: Rscript {0}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: test python installation
        run: |
          python --version

      - name: Run setup
        run:
          sh ./tools/setup.sh

      - name: Quick test
        run: |
          sessionInfo()
        shell: Rscript {0}

      - name: Run benchmarks
        run: |
          benchtorch:::run_benchmark()
        shell: Rscript {0}

      - uses: EndBug/add-and-commit@v9
        with:
          add: "results/*"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add new results"



